name: test_get-predictions v2
# needs DESCRIPTION file

## set timer (17:25 utc)
#on:
#  schedule:
#  - cron: 25 17 * * *
  
## run script on push
on:
  push:
    branches: 
      - main

jobs:
  RScript:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::prophet
      - run: Rscript script.R

     # add file to data folder, commit, push
      - name: commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "Scheduled Github Action on $(date)"
          git push origin main
