name: get-predictions-python

on: push

# or set timer (runs every 2nd day at 17:25 utc)
#on:
#  schedule:
#  - cron: 25 17 */2 * *

jobs:
  get-data-from-csv:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        run: python script.py
        
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "Scheduled Github Action on $(date)"
          git push origin main
